/*
===============================================================================
MEDLYTICS - SCRIPT DML

INTEGRANTES:
GABRIELA MARI / RM572357
JULIA GOMES / RM572494
MARIA EDUARDA CAMPOS / RM569546
===============================================================================
*/

SET DEFINE OFF;


-------------------------------------------------------------------------------
-- 1. CARGA DE HOSPITAIS
-------------------------------------------------------------------------------

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '2000660',
    '1200452000660',
    12,
    'AC',
    'SENADOR GUIOMARD',
    120045,
    'PREFEITURA MUNICIPAL DE SENADOR GUIOMARD',
    'CENTRO DE SAUDE MARIA DO SOCORRO CAVALCANTE',
    '69925000',
    'PEDRO ALEIXO',
    NULL,
    'CENTRO',
    '68 32322652',
    'SEMSASGUIOMARD@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '2001594',
    '1200352001594',
    12,
    'AC',
    'MARECHAL THAUMATURGO',
    120035,
    'SECRETARIA DE ESTADO DE SAUDE',
    'UNIDADE MISTA DE MARECHAL THAUMATURGO',
    '69983000',
    'RUA 05 DE NOVEMBRO',
    NULL,
    'CENTRO',
    '68 992177392',
    'UMMT2018@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '44237',
    '2704300044237',
    27,
    'AL',
    'MACEIO',
    270430,
    'SECRETARIA MUNICIPAL DE SAUDE',
    'CENTRAL MUNICIPAL DE REDE DE FRIO DE MACEIO',
    '57071612',
    'LOT DURVILLE',
    '10',
    'CLIMA BOM',
    '82 3312 5468',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '50636',
    '2708400050636',
    27,
    'AL',
    'SAO JOSE DA TAPERA',
    270840,
    'PREFEITURA MUNICIPAL DE SAO JOSE DA TAPERA',
    'MELHOR EM CASA SAO JOSE DA TAPERA',
    '57445000',
    'RUA 1 DE MAIO',
    NULL,
    'CENTRO',
    NULL,
    'GENEFLIDES@YAHOO.COM.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '12211',
    '1302600012211',
    13,
    'AM',
    'MANAUS',
    130260,
    'SUPERINTENDENCIA DA ZONA FRANCA DE MANAUS',
    'SUFRAMA',
    '69075830',
    'AVENIDA MINISTRO MARIO ANDREAZZA',
    '1424',
    'DISTRITO INDUSTRIAL',
    '92 33217074',
    'SUFRAMA@SUFRAMA.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '32093',
    '1300680032093',
    13,
    'AM',
    'BOA VISTA DO RAMOS',
    130068,
    'ACADEMIA DA SAUDE MARIA EMILIA DE SOUZA SANTOS',
    'ACADEMIA DA SAUDE MARIA EMILIA DE SOUZA SANTOS',
    '69220066',
    'RUA PADRE HENRIQUE PAGANI',
    NULL,
    'ESPERANCA',
    NULL,
    'SMS-BOAVISTADORAMOS@SAUDE.AM.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '39624',
    '1600300039624',
    16,
    'AP',
    'MACAPA',
    160030,
    'MUNICIPIO DE MACAPA',
    'PMM CEO CENTRO DE ESPECIALIDADES ODONTOLOGICAS DE MACAPA',
    '68908782',
    'RUA ADILSON JOSE PINTO PEREIRA',
    '3104',
    'RENASCER',
    '96 99713850',
    'CENTROODONTOLOGICOPMM153@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '2020157',
    '1600272020157',
    16,
    'AP',
    'LARANJAL DO JARI',
    160027,
    'PREFEITURA MUNICIPAL DE LARANJAL DO JARI',
    'PMLJ UBS CENTRO VANEA SILVA',
    '68920000',
    'RUA DA USINA',
    NULL,
    'CENTRO',
    '96 36211888',
    'SAUDE@LARANJALDOJARI.AP.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '3778',
    '2927400003778',
    29,
    'BA',
    'SALVADOR',
    292740,
    'BAHIA SECRETARIA DE SAUDE DO ESTADO',
    'HOSPITAL ESTADUAL DA MULHER',
    '40411900',
    'RUA BARAO DE COTEGIPE',
    '1153',
    'ROMA',
    '71 39950680',
    'FATURAMENTOHM.IFF@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '3840',
    '2927400003840',
    29,
    'BA',
    'SALVADOR',
    292740,
    'BAHIA SECRETARIA DE SAUDE DO ESTADO',
    'MATERNIDADE ALBERT SABIN',
    '41342395',
    'ESTRADA DO COQUEIRO GRANDE',
    NULL,
    'CAJAZEIRAS',
    '71 32535353',
    'SESAB.MASABIN@SAUDE.GOV.BA.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '46663',
    '2308600046663',
    23,
    'CE',
    'MONSENHOR TABOSA',
    230860,
    'PREF M MONSENHOR TABOSA',
    'EQUPE DE SAUDE DA FAMILIA DE SANTANA',
    '63780000',
    'DISTRITO DE SANTANA',
    NULL,
    'ZONA RURAL',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '47287',
    '2310400047287',
    23,
    'CE',
    'PARAMOTI',
    231040,
    'PREFEITURA MUNICIPAL DE PARAMOTI',
    'ACADEMIA DA SAUDE DE PARAMOTI',
    '62736000',
    'AVENIDA HONORATO FEIJO',
    NULL,
    'BELA VISTA',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '10480',
    '5300100010480',
    53,
    'DF',
    'BRASILIA',
    530010,
    'HOSPITAL REGIONAL DE CEILANDIA',
    'HOSPITAL REGIONAL DE CEILANDIA',
    '73340793',
    'QNM AREA ESPECIAL',
    NULL,
    'CEILANDIA',
    NULL,
    'DAS.DRSC@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '10499',
    '5300100010499',
    53,
    'DF',
    'BRASILIA',
    530010,
    'HOSPITAL REGIONAL DE TAGUATINGA',
    'HRT HOSPITAL REGIONAL DE TAGUATINGA',
    '72115902',
    'SETOR C NORTE',
    '24',
    'TAGUATINGA',
    '61 20171700',
    'SUPER.SUDOESTE.DF@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '11797',
    '3205300011797',
    32,
    'ES',
    'VITORIA',
    320530,
    'MUNICIPIO DE VITORIA',
    'UNIDADE BASICA DE SAUDE JESUS DE NAZARETH',
    '29052044',
    'RUA HELENA MULLER',
    '168',
    'JESUS DE NAZARETH',
    '27 33826740',
    'USJNAZARETH@CORREIO1.VITORIA.ES.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '11800',
    '3205300011800',
    32,
    'ES',
    'VITORIA',
    320530,
    'SECRETARIA DE ESTADO DA SAUDE',
    'HOSPITAL INFANTIL NOSSA SENHORA DA GLORIA',
    '29056030',
    'ALAMEDA MARY UBIRAJARA',
    '205',
    'SANTA LUCIA',
    '27 31371804',
    'CONTABILIDADE@SAUDE.ES.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '24074',
    '5208700024074',
    52,
    'GO',
    'GOIANIA',
    520870,
    'SECRETARIA MUNICIPAL DE SAUDE',
    'HOSPITAL MUNICIPAL DA MULHER E MATERNIDADE CELIA CAMARA',
    '74495160',
    'AV SENADOR CANEDO ESQ AV GERCINA BORGES TEIXEIRA',
    NULL,
    'CONJUNTO VERA CRUZ',
    NULL,
    'ANGELICAASANTANA@HOTMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '118192',
    '5208700118192',
    52,
    'GO',
    'GOIANIA',
    520870,
    'SECRETARIA MUNICIPAL DE SAUDE',
    'REDE DE FRIO DO MUNICIPIO DE GOIANIA',
    '74884092',
    'AVENIDA DO CERRADO',
    '999',
    'PARK LOZANDES',
    '62 35243812',
    'DIVISAODEIMUNIZACAO@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '28916',
    '2107800028916',
    21,
    'MA',
    'PARNARAMA',
    210780,
    'MUNICIPIO DE PARNARAMA',
    'UNIDADE BASICA DE SAUDE TERRA NOVA',
    '65640000',
    'AV BENEDITO MUNIZ',
    NULL,
    'TERRA NOVA',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '29769',
    '2110200029769',
    21,
    'MA',
    'SANTA RITA',
    211020,
    'MUNICIPIO DE SANTA RITA',
    'UNIDADE BASICA DE SAUDE CARIONGO',
    '65145000',
    'POVOADO CARIONGO',
    NULL,
    'CARIONGO',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '22543',
    '3106200022543',
    31,
    'MG',
    'BELO HORIZONTE',
    310620,
    'MUNICIPIO DE BELO HORIZONTE',
    'CENTRO DE SAUDE MARIA MADALENA TEODORO LINDEIA',
    '30690170',
    'RUA FLOR DE MAIO',
    '172',
    'LINDEIA',
    '31 32775825',
    'C.S.LINDEIA@PBH.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '22551',
    '3106200022551',
    31,
    'MG',
    'BELO HORIZONTE',
    310620,
    'MUNICIPIO DE BELO HORIZONTE',
    'CENTRO DE SAUDE ITAIPU JATOBA',
    '30692640',
    'RUA WANDERLEY DE SALES BARBOSA',
    '350',
    'MARILANDIA',
    '31 32775822',
    'ITAIPU.JATOBA@PBH.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '9725',
    '5002700009725',
    50,
    'MS',
    'CAMPO GRANDE',
    500270,
    'FUNDACAO SERVICOS DE SAUDE DE MATO GROSSO DO SUL SAUDE MS',
    'HOSPITAL REGIONAL DE MATO GROSSO DO SUL',
    '79084180',
    'AVENIDA ENGENHEIRO LUTHERO LOPES',
    '36',
    'AERO RANCHO V',
    '67 33782500',
    'PRESIDENCIA@FUNSAU.MS.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '2371618',
    '5000202371618',
    50,
    'MS',
    'AGUA CLARA',
    500020,
    'PREFEITURA MUNICIPAL DE AGUA CLARA',
    'HOSPITAL MUNICIPAL NOSSA SENHORA APARECIDA',
    '79680037',
    'RUA FRANCISCO VIEIRA',
    NULL,
    'NOVA AGUA CLARA',
    '67 32391461',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '71773',
    '5106000071773',
    51,
    'MT',
    'NORTELANDIA',
    510600,
    'FUNDO MUNICIPAL DE SAUDE DE NORTELANDIA',
    'HOSPITAL MUNICIPAL DE NORTELANDIA MT',
    '78430000',
    'DOMINGOS DE DEUS DA SILVA',
    '328',
    'CENTRO',
    '65 33461411',
    'SMS_NORTELANDIA@HOTMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '171557',
    '5107600171557',
    51,
    'MT',
    'RONDONOPOLIS',
    510760,
    'MUNICIPIO DE RONDONOPOLIS',
    'HOSPITAL MUNICIPAL CRISTYAN MARY DA SILVEIRA E LIMA',
    '78710010',
    'AV ROTARY INTERNACIONAL',
    NULL,
    'VILA AURORA III',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '4790',
    '1501400004790',
    15,
    'PA',
    'BELEM',
    150140,
    'SECRETARIA DE ESTADO DE SAUDE PUBLICA',
    'POLICLINICA ESPECIALIZADA DO PARA UNIDADE MARCO',
    '66095110',
    'AVENIDA DOUTOR FREITAS',
    '2683',
    'MARCO',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '7668',
    '1502400007668',
    15,
    'PA',
    'CASTANHAL',
    150240,
    'PREFEITURA MUNICIPAL DE CASTANHAL',
    'CAE CENTRO DE ATENDIMENTO ESPECIALIZADO',
    '68745000',
    'AVENIDA BARAO DO RIO BRANCO',
    '1821',
    'CENTRO',
    '09 37211099',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '900613',
    '2504800900613',
    25,
    'PB',
    'COREMAS',
    250480,
    'MUNICIPIO DE COREMAS',
    'UNIDADE BASICA DE SAUDE PSF VIII',
    '58770000',
    'RUA SANTA RITA',
    NULL,
    'CENTRO',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '905054',
    '2506000905054',
    25,
    'PB',
    'ESPERANCA',
    250600,
    'PREFEITURA MUNICIPAL DE ESPERANCA',
    'CENTRO DA MULHER CLAUDIA ROBERTA GOMES SILVA DANTAS',
    '58135000',
    'RUA JUSCELINO KUBITSCHEK',
    NULL,
    'CENTRO',
    '83 35021341',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '35',
    '2602900000035',
    26,
    'PE',
    'CABO DE SANTO AGOSTINHO',
    260290,
    'PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO',
    'HOSPITAL MENDO SAMPAIO',
    '54535430',
    'BR 101 SUL KM 33',
    NULL,
    'CHARNECA',
    '81 35210857',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '426',
    '2611600000426',
    26,
    'PE',
    'RECIFE',
    261160,
    'SECRETARIA DE SAUDE',
    'HOSPITAL OTAVIO DE FREITAS',
    '50920592',
    'RUA APRIGIO GUIMARAES',
    NULL,
    'TEJIPIO',
    '81 31828500',
    'DIRETORIAHOF@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '2315378',
    '2208302315378',
    22,
    'PI',
    'PIRACURUCA',
    220830,
    'SECRETARIA MUNICIPAL DE SAUDE',
    'PRONTO SOCORRO MUNICIPAL DE PIRACURUCA',
    '64240000',
    'AV CEL PEDRO DE BRITO',
    '1299',
    'CENTRO',
    '86 33431262',
    'SMSPIRACURUCA@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '2315386',
    '2208302315386',
    22,
    'PI',
    'PIRACURUCA',
    220830,
    'SAO RAIMUNDO MATERNIDADE MUNICIPAL',
    'MATERNIDADE MUNICIPAL DE PIRACURUCA',
    '64240000',
    'AV SENADOR GERVASIO',
    NULL,
    'FATIMA',
    '86 33431228',
    'SMSPIRACURUCA@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '13749',
    '4104000013749',
    41,
    'PR',
    'CAMPINA GRANDE DO SUL',
    410400,
    'MUNICIPIO DE CAMPINA GRANDE DO SUL',
    'UNIDADE DE SAUDE PEDRO CASEMIRO RODRIGUES',
    '83438890',
    'BR 116 KM 38',
    NULL,
    'CAPIVARI GRANDE',
    '41 31627145',
    'SAUDE.CAMPINA@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '13811',
    '4104200013811',
    41,
    'PR',
    'CAMPO LARGO',
    410420,
    'PREFEITURA MUNICIPAL DE CAMPO LARGO',
    'NUCLEO INTEGRADO DE SAUDE NISIII',
    '83601180',
    'BARAO DO RIO BRANCO',
    '1415',
    'CENTRO',
    '41 32915247',
    'SAUDE@CAMPOLARGO.PR.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '12556',
    '3303300012556',
    33,
    'RJ',
    'NITEROI',
    330330,
    'FUNDACAO MUNICIPAL DE SAUDE DE NITEROI',
    'HOSPITAL ORENCIO DE FREITAS',
    '24111000',
    'MACHADO',
    NULL,
    'BARRETO',
    '21 26203434',
    'DIRECAOHOF@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '105317',
    '3303300105317',
    33,
    'RJ',
    'NITEROI',
    330330,
    'FUNDACAO MUNICIPAL DE SAUDE DE NITEROI',
    'HOSPITAL MUNICIPAL OCEANICO DR GILSON CANTARINO HMOGC',
    '24350630',
    'DOUTOR RAUL DE OLIVEIRA RODRIGUES',
    '382',
    'PIRATININGA',
    '21 31803948',
    'CONTABILIDADESAUDEDENITEROI@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '107816',
    '2400300107816',
    24,
    'RN',
    'AFONSO BEZERRA',
    240030,
    'MUNICIPAL DE AFONSO BEZERRA',
    'HOSPITAL MUNICIPAL DE AFONSO BEZERRA',
    '59510000',
    'AV BATISTA MONTENEGRO',
    '286',
    'CENTRO',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '104884',
    '2412000104884',
    24,
    'RN',
    'SAO GONCALO DO AMARANTE',
    241200,
    'MUNICIPIO DE SAO GONCALO DO AMARANTE',
    'HOSPITAL DAS CLINICAS DE SAO GONCALO',
    '59299400',
    'ESTRADA DE GUANDUBA',
    NULL,
    'CENTRO',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '109061',
    '1100300109061',
    11,
    'RO',
    'VILHENA',
    110030,
    'MUNICIPIO DE VILHENA',
    'UNIDADE BASICA DE SAUDE ST 12 DR LUIS ALBERTO VALDEZ MARQUEZ',
    '76987444',
    'AVENIDA PRESIDENTE TANCREDO NEVES',
    '7997',
    'JARDIM ARAUCARIA',
    '69 33211480',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '253987',
    '1100200253987',
    11,
    'RO',
    'PORTO VELHO',
    110020,
    'RONDONIA SECRETARIA DE ESTADO DA SAUDE',
    'HOSPITAL DE TRATAMENTO A COVID 19 DE RONDONIA UNIDADE II',
    '76813604',
    'PETROLINA',
    '9960',
    'MARIANA',
    NULL,
    'HOSPITALCAMPANHAZONALESTE@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '78484',
    '1400200078484',
    14,
    'RR',
    'CARACARAI',
    140020,
    'MUNICIPIO DE CARACARAI',
    'UNIDADE BASICA DE SAUDE NILZA DA SILVA SOUZA',
    '69360000',
    'AV AMOR PERFEITO',
    NULL,
    'SANTO ANTONIO',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '81906',
    '1400150081906',
    14,
    'RR',
    'BONFIM',
    140015,
    'DISTRITO SANITARIO ESPECIAL INDIGENA LESTE DE RORAIMA',
    'UBS DALVA OLIVEIRA DE SOUZA COM IND MOSCOU',
    '69380000',
    'COMUNIDADE INDIGENA MOSCOU',
    NULL,
    'COMUNIDADE INDIGENA',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '58394',
    '4321500058394',
    43,
    'RS',
    'TORRES',
    432150,
    'CLINICA MUNICIPAL DE ESPECIALIDADES',
    'CLINICA MUNICIPAL DE ESPECIALIDADES',
    '95560000',
    'RUA FIRMINO PAIM',
    '988',
    'CENTRO',
    NULL,
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '58807',
    '4313400058807',
    43,
    'RS',
    'NOVO HAMBURGO',
    431340,
    'CER CENTRO ESPEC REAB AUD FISICA INTELEC E VISUAL',
    'CER IV NOVO HAMBURGO',
    '93415520',
    'DOUTOR JOAO DANIEL HILLEBRAND',
    '2200',
    'RONDONIA',
    NULL,
    'DIRETORGERAL.CER@GMAIL.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '19283',
    '4205400019283',
    42,
    'SC',
    'FLORIANOPOLIS',
    420540,
    'SECRETARIA DE ESTADO DA SAUDE',
    'MATERNIDADE CARMELA DUTRA',
    '88015270',
    'IRMA BENWARDA',
    '208',
    'CENTRO',
    '48 36643900',
    'MCD@SAUDE.SC.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '19305',
    '4205400019305',
    42,
    'SC',
    'FLORIANOPOLIS',
    420540,
    'SECRETARIA DE ESTADO DA SAUDE',
    'HOSPITAL FLORIANOPOLIS',
    '88090350',
    'SANTA RITA DE CASSIA RUA',
    '1665',
    'COLONINHA',
    '48 32817800',
    'ADM.HF@IMAS.NET.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '2421089',
    '2804502421089',
    28,
    'SE',
    'NOSSA SENHORA DA GLORIA',
    280450,
    'PREFEITURA MUNICIPAL DE NOSSA SENHORA DA GLORIA SE',
    'CLINICA DE SAUDE DA FAMILIA ROSA MARIA DOS SANTOS SOBRINHO',
    '49680000',
    'BAIRRO BRASILIA',
    NULL,
    'BRASILIA',
    '79 34111713',
    'SAUDEGLRORIA@HOTMAIT.COM'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '2372',
    '2800300002372',
    28,
    'SE',
    'ARACAJU',
    280030,
    'SECRETARIA MUNICIPAL DE SAUDE DE ARACAJU',
    'HOSPITAL MUNICIPAL ZONA SUL DES FERNANDO FRANCO',
    '49030290',
    'AV TARCISIO DANIEL',
    '1',
    'FAROLANDIA',
    '79 32120503',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '8028',
    '3534400008028',
    35,
    'SP',
    'OSASCO',
    353440,
    'PREFEITURA DO MUNICIPIO DE OSASCO',
    'HOSPITAL MUNICIPAL ANTONIO GIGLIO',
    '6013070',
    'RUA PEDRO FIORETTI',
    '48',
    'CENTRO',
    '11 21839333',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '8737',
    '3547800008737',
    35,
    'SP',
    'SANTO ANDRE',
    354780,
    'PREFEITURA MUNICIPAL DE SANTO ANDRE',
    'CENTRO MEDICO DE ESPECIALIDADES XAVIER DE TOLEDO',
    '9010130',
    'RUA XAVIER DE TOLEDO',
    '517',
    'CENTRO',
    '11 44796800',
    NULL
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '49298',
    '1702200049298',
    17,
    'TO',
    'ARAGUATINS',
    170220,
    'UNIDADE BASICA DE SAUDE JOAO BARBOSA DA SILVA',
    'UNIDADE BASICA DE SAUDE JOAO BARBOSA DA SILVA',
    '77950000',
    'RUA MARECHAL CASTELO BRANCO',
    NULL,
    'SANTA TEREZA',
    NULL,
    'ARAGUATINS@SAUDE.TO.GOV.BR'
);

INSERT INTO TB_HOSPITAIS (
    CO_CNES,
    CO_UNIDADE,
    CO_UF,
    NO_UF,
    NO_MUNICIPIO,
    CO_IBGE,
    NO_RAZAO_SOCIAL,
    NO_FANTASIA,
    CO_CEP,
    NO_LOGRADOURO,
    NU_ENDERECO,
    NO_BAIRRO,
    NU_TELEFONE,
    NO_EMAIL
)
VALUES (
    '69078',
    '1702550069078',
    17,
    'TO',
    'AUGUSTINOPOLIS',
    170255,
    'PREFEITURA MUNICIPAL DE AUGUSTINOPOLIS',
    'UNIDADE BASICA DE SAUDE DA FAMILIA VI',
    '77960000',
    'RUA MAURICIO GOMES DOS SANTOS',
    NULL,
    'JARDIM PRIMAVERA',
    NULL,
    NULL
);



-------------------------------------------------------------------------------
-- 2. CARGA DE LEITOS DE UTI
-------------------------------------------------------------------------------

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1200452000660',
    9,
    4,
    5,
    27,
    13,
    14,
    58,
    33,
    25,
    23,
    11,
    12,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1200352001594',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2704300044237',
    41,
    31,
    10,
    27,
    18,
    9,
    18,
    10,
    8,
    47,
    22,
    25,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2708400050636',
    29,
    23,
    6,
    49,
    27,
    22,
    7,
    4,
    3,
    38,
    27,
    11,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1302600012211',
    28,
    25,
    3,
    22,
    13,
    9,
    12,
    10,
    2,
    56,
    42,
    14,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1300680032093',
    52,
    31,
    21,
    14,
    10,
    4,
    35,
    18,
    17,
    52,
    33,
    19,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1600300039624',
    9,
    6,
    3,
    23,
    12,
    11,
    35,
    19,
    16,
    46,
    27,
    19,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1600272020157',
    43,
    28,
    15,
    6,
    5,
    1,
    25,
    18,
    7,
    38,
    26,
    12,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2927400003778',
    10,
    5,
    5,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2927400003840',
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    2,
    2,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2308600046663',
    33,
    22,
    11,
    47,
    30,
    17,
    30,
    18,
    12,
    11,
    5,
    6,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2310400047287',
    58,
    32,
    26,
    44,
    32,
    12,
    49,
    39,
    10,
    25,
    13,
    12,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '5300100010480',
    10,
    8,
    2,
    0,
    0,
    0,
    10,
    9,
    1,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '5300100010499',
    8,
    5,
    3,
    8,
    6,
    2,
    8,
    5,
    3,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '3205300011797',
    44,
    36,
    8,
    44,
    21,
    23,
    16,
    8,
    8,
    11,
    8,
    3,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '3205300011800',
    0,
    0,
    0,
    16,
    10,
    6,
    9,
    4,
    5,
    6,
    4,
    2,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '5208700024074',
    30,
    18,
    12,
    0,
    0,
    0,
    10,
    6,
    4,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '5208700118192',
    12,
    10,
    2,
    32,
    22,
    10,
    21,
    11,
    10,
    52,
    32,
    20,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2107800028916',
    51,
    41,
    10,
    56,
    34,
    22,
    39,
    29,
    10,
    20,
    14,
    6,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2110200029769',
    29,
    18,
    11,
    13,
    7,
    6,
    33,
    17,
    16,
    29,
    14,
    15,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '3106200022543',
    32,
    19,
    13,
    32,
    16,
    16,
    54,
    37,
    17,
    34,
    28,
    6,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '3106200022551',
    25,
    19,
    6,
    43,
    31,
    12,
    19,
    14,
    5,
    18,
    9,
    9,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '5002700009725',
    47,
    24,
    23,
    8,
    4,
    4,
    10,
    7,
    3,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '5000202371618',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '5106000071773',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '5107600171557',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1501400004790',
    27,
    20,
    7,
    18,
    13,
    5,
    34,
    27,
    7,
    51,
    45,
    6,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1502400007668',
    50,
    38,
    12,
    21,
    10,
    11,
    7,
    4,
    3,
    49,
    40,
    9,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2504800900613',
    34,
    27,
    7,
    42,
    37,
    5,
    21,
    11,
    10,
    57,
    46,
    11,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2506000905054',
    29,
    19,
    10,
    39,
    26,
    13,
    28,
    24,
    4,
    10,
    7,
    3,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2602900000035',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2611600000426',
    50,
    26,
    24,
    29,
    14,
    15,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2208302315378',
    10,
    5,
    5,
    57,
    38,
    19,
    13,
    9,
    4,
    31,
    21,
    10,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2208302315386',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '4104000013749',
    53,
    35,
    18,
    23,
    20,
    3,
    10,
    9,
    1,
    24,
    20,
    4,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '4104200013811',
    8,
    6,
    2,
    11,
    8,
    3,
    46,
    27,
    19,
    13,
    9,
    4,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '3303300012556',
    6,
    5,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '3303300105317',
    10,
    7,
    3,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2400300107816',
    20,
    14,
    6,
    25,
    15,
    10,
    17,
    12,
    5,
    22,
    13,
    9,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2412000104884',
    39,
    27,
    12,
    54,
    37,
    17,
    54,
    40,
    14,
    22,
    11,
    11,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1100300109061',
    14,
    8,
    6,
    32,
    21,
    11,
    11,
    5,
    6,
    55,
    37,
    18,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1100200253987',
    46,
    21,
    25,
    43,
    20,
    23,
    33,
    17,
    16,
    12,
    8,
    4,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1400200078484',
    43,
    28,
    15,
    30,
    25,
    5,
    30,
    19,
    11,
    55,
    31,
    24,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1400150081906',
    24,
    13,
    11,
    19,
    16,
    3,
    22,
    19,
    3,
    55,
    34,
    21,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '4321500058394',
    8,
    5,
    3,
    47,
    24,
    23,
    6,
    4,
    2,
    37,
    23,
    14,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '4313400058807',
    58,
    48,
    10,
    58,
    41,
    17,
    47,
    41,
    6,
    14,
    8,
    6,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '4205400019283',
    0,
    0,
    0,
    0,
    0,
    0,
    10,
    8,
    2,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '4205400019305',
    20,
    10,
    10,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2804502421089',
    42,
    24,
    18,
    19,
    11,
    8,
    27,
    22,
    5,
    36,
    21,
    15,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '2800300002372',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '3534400008028',
    20,
    15,
    5,
    8,
    6,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '3547800008737',
    15,
    11,
    4,
    29,
    23,
    6,
    10,
    8,
    2,
    11,
    7,
    4,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1702200049298',
    25,
    20,
    5,
    45,
    22,
    23,
    45,
    36,
    9,
    34,
    20,
    14,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);

INSERT INTO TB_LEITOS (
    CO_UNIDADE,
    UTI_ADULTA_TOTAL,
    UTI_ADULTA_OCUPADA,
    UTI_ADULTA_DISPONIVEL,
    UTI_PEDIATRICA_TOTAL,
    UTI_PEDIATRICA_OCUPADA,
    UTI_PEDIATRICA_DISPONIVEL,
    UTI_NEONATAL_TOTAL,
    UTI_NEONATAL_OCUPADA,
    UTI_NEONATAL_DISPONIVEL,
    UTI_QUEIMADOS_TOTAL,
    UTI_QUEIMADOS_OCUPADA,
    UTI_QUEIMADOS_DISPONIVEL,
    DATA_ULTIMA_ATUALIZACAO
)
VALUES (
    '1702550069078',
    30,
    22,
    8,
    19,
    16,
    3,
    46,
    26,
    20,
    6,
    4,
    2,
    TO_DATE('05/01/2026', 'DD/MM/YYYY')
);



-------------------------------------------------------------------------------
-- 3. CARGA DE INTERNACOES
-------------------------------------------------------------------------------

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    1,
    '1200452000660',
    TO_DATE('07/01/2026', 'DD/MM/YYYY'),
    TO_DATE('19/01/2026', 'DD/MM/YYYY'),
    12,
    'I21',
    'INFARTO AGUDO DO MIOCÁRDIO',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    2,
    '1200352001594',
    TO_DATE('23/06/2026', 'DD/MM/YYYY'),
    TO_DATE('05/07/2026', 'DD/MM/YYYY'),
    12,
    'N39',
    'INFECÇÃO URINÁRIA',
    'ELETIVO',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    3,
    '2704300044237',
    TO_DATE('08/01/2026', 'DD/MM/YYYY'),
    TO_DATE('10/01/2026', 'DD/MM/YYYY'),
    2,
    'A90',
    'DENGUE',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    4,
    '2708400050636',
    TO_DATE('20/02/2026', 'DD/MM/YYYY'),
    TO_DATE('04/03/2026', 'DD/MM/YYYY'),
    12,
    'J18',
    'PNEUMONIA',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    5,
    '1302600012211',
    TO_DATE('31/05/2026', 'DD/MM/YYYY'),
    TO_DATE('05/06/2026', 'DD/MM/YYYY'),
    5,
    'J18',
    'PNEUMONIA',
    'ELETIVO',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    6,
    '1300680032093',
    TO_DATE('28/06/2026', 'DD/MM/YYYY'),
    TO_DATE('05/07/2026', 'DD/MM/YYYY'),
    7,
    'N39',
    'INFECÇÃO URINÁRIA',
    'EMERGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    7,
    '1600300039624',
    TO_DATE('28/03/2026', 'DD/MM/YYYY'),
    TO_DATE('30/03/2026', 'DD/MM/YYYY'),
    2,
    'U07.1',
    'COVID-19',
    'EMERGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    8,
    '1600272020157',
    TO_DATE('04/06/2026', 'DD/MM/YYYY'),
    TO_DATE('09/06/2026', 'DD/MM/YYYY'),
    5,
    'K35',
    'APENDICITE',
    'ELETIVO',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    9,
    '2927400003778',
    TO_DATE('07/04/2026', 'DD/MM/YYYY'),
    TO_DATE('09/04/2026', 'DD/MM/YYYY'),
    2,
    'J45',
    'ASMA',
    'URGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    10,
    '2927400003840',
    TO_DATE('03/04/2026', 'DD/MM/YYYY'),
    TO_DATE('13/04/2026', 'DD/MM/YYYY'),
    10,
    'I21',
    'INFARTO AGUDO DO MIOCÁRDIO',
    'EMERGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    11,
    '2308600046663',
    TO_DATE('16/03/2026', 'DD/MM/YYYY'),
    TO_DATE('18/03/2026', 'DD/MM/YYYY'),
    2,
    'I21',
    'INFARTO AGUDO DO MIOCÁRDIO',
    'ELETIVO',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    12,
    '2310400047287',
    TO_DATE('27/04/2026', 'DD/MM/YYYY'),
    TO_DATE('08/05/2026', 'DD/MM/YYYY'),
    11,
    'A90',
    'DENGUE',
    'ELETIVO',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    13,
    '5300100010480',
    TO_DATE('21/06/2026', 'DD/MM/YYYY'),
    TO_DATE('26/06/2026', 'DD/MM/YYYY'),
    5,
    'A90',
    'DENGUE',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    14,
    '5300100010499',
    TO_DATE('12/06/2026', 'DD/MM/YYYY'),
    TO_DATE('15/06/2026', 'DD/MM/YYYY'),
    3,
    'J18',
    'PNEUMONIA',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    15,
    '3205300011797',
    TO_DATE('11/03/2026', 'DD/MM/YYYY'),
    TO_DATE('26/03/2026', 'DD/MM/YYYY'),
    15,
    'J45',
    'ASMA',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    16,
    '3205300011800',
    TO_DATE('15/01/2026', 'DD/MM/YYYY'),
    TO_DATE('19/01/2026', 'DD/MM/YYYY'),
    4,
    'I21',
    'INFARTO AGUDO DO MIOCÁRDIO',
    'ELETIVO',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    17,
    '5208700024074',
    TO_DATE('17/01/2026', 'DD/MM/YYYY'),
    TO_DATE('21/01/2026', 'DD/MM/YYYY'),
    4,
    'A90',
    'DENGUE',
    'ELETIVO',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    18,
    '5208700118192',
    TO_DATE('24/02/2026', 'DD/MM/YYYY'),
    TO_DATE('07/03/2026', 'DD/MM/YYYY'),
    11,
    'I21',
    'INFARTO AGUDO DO MIOCÁRDIO',
    'URGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    19,
    '2107800028916',
    TO_DATE('06/02/2026', 'DD/MM/YYYY'),
    TO_DATE('11/02/2026', 'DD/MM/YYYY'),
    5,
    'I21',
    'INFARTO AGUDO DO MIOCÁRDIO',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    20,
    '2110200029769',
    TO_DATE('30/05/2026', 'DD/MM/YYYY'),
    TO_DATE('06/06/2026', 'DD/MM/YYYY'),
    7,
    'J45',
    'ASMA',
    'ELETIVO',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    21,
    '3106200022543',
    TO_DATE('05/02/2026', 'DD/MM/YYYY'),
    TO_DATE('14/02/2026', 'DD/MM/YYYY'),
    9,
    'J18',
    'PNEUMONIA',
    'URGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    22,
    '3106200022551',
    TO_DATE('09/02/2026', 'DD/MM/YYYY'),
    TO_DATE('20/02/2026', 'DD/MM/YYYY'),
    11,
    'K35',
    'APENDICITE',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    23,
    '5002700009725',
    TO_DATE('09/04/2026', 'DD/MM/YYYY'),
    TO_DATE('16/04/2026', 'DD/MM/YYYY'),
    7,
    'J45',
    'ASMA',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    24,
    '5000202371618',
    TO_DATE('22/05/2026', 'DD/MM/YYYY'),
    TO_DATE('05/06/2026', 'DD/MM/YYYY'),
    14,
    'A90',
    'DENGUE',
    'ELETIVO',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    25,
    '5106000071773',
    TO_DATE('18/05/2026', 'DD/MM/YYYY'),
    TO_DATE('31/05/2026', 'DD/MM/YYYY'),
    13,
    'J18',
    'PNEUMONIA',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    26,
    '5107600171557',
    TO_DATE('22/04/2026', 'DD/MM/YYYY'),
    TO_DATE('25/04/2026', 'DD/MM/YYYY'),
    3,
    'J18',
    'PNEUMONIA',
    'URGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    27,
    '1501400004790',
    TO_DATE('09/03/2026', 'DD/MM/YYYY'),
    TO_DATE('18/03/2026', 'DD/MM/YYYY'),
    9,
    'K35',
    'APENDICITE',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    28,
    '1502400007668',
    TO_DATE('10/06/2026', 'DD/MM/YYYY'),
    TO_DATE('15/06/2026', 'DD/MM/YYYY'),
    5,
    'J18',
    'PNEUMONIA',
    'ELETIVO',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    29,
    '2504800900613',
    TO_DATE('06/04/2026', 'DD/MM/YYYY'),
    TO_DATE('19/04/2026', 'DD/MM/YYYY'),
    13,
    'J18',
    'PNEUMONIA',
    'EMERGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    30,
    '2506000905054',
    TO_DATE('01/01/2026', 'DD/MM/YYYY'),
    TO_DATE('11/01/2026', 'DD/MM/YYYY'),
    10,
    'E11',
    'DIABETES MELLITUS',
    'EMERGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    31,
    '2602900000035',
    TO_DATE('20/03/2026', 'DD/MM/YYYY'),
    TO_DATE('24/03/2026', 'DD/MM/YYYY'),
    4,
    'E11',
    'DIABETES MELLITUS',
    'EMERGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    32,
    '2611600000426',
    TO_DATE('22/01/2026', 'DD/MM/YYYY'),
    TO_DATE('03/02/2026', 'DD/MM/YYYY'),
    12,
    'E11',
    'DIABETES MELLITUS',
    'URGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    33,
    '2208302315378',
    TO_DATE('02/02/2026', 'DD/MM/YYYY'),
    TO_DATE('05/02/2026', 'DD/MM/YYYY'),
    3,
    'N39',
    'INFECÇÃO URINÁRIA',
    'URGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    34,
    '2208302315386',
    TO_DATE('16/05/2026', 'DD/MM/YYYY'),
    TO_DATE('30/05/2026', 'DD/MM/YYYY'),
    14,
    'J18',
    'PNEUMONIA',
    'URGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    35,
    '4104000013749',
    TO_DATE('26/06/2026', 'DD/MM/YYYY'),
    TO_DATE('30/06/2026', 'DD/MM/YYYY'),
    4,
    'E11',
    'DIABETES MELLITUS',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    36,
    '4104200013811',
    TO_DATE('06/04/2026', 'DD/MM/YYYY'),
    TO_DATE('14/04/2026', 'DD/MM/YYYY'),
    8,
    'I21',
    'INFARTO AGUDO DO MIOCÁRDIO',
    'ELETIVO',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    37,
    '3303300012556',
    TO_DATE('17/01/2026', 'DD/MM/YYYY'),
    TO_DATE('23/01/2026', 'DD/MM/YYYY'),
    6,
    'J18',
    'PNEUMONIA',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    38,
    '3303300105317',
    TO_DATE('02/01/2026', 'DD/MM/YYYY'),
    TO_DATE('04/01/2026', 'DD/MM/YYYY'),
    2,
    'J45',
    'ASMA',
    'URGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    39,
    '2400300107816',
    TO_DATE('09/01/2026', 'DD/MM/YYYY'),
    TO_DATE('23/01/2026', 'DD/MM/YYYY'),
    14,
    'J18',
    'PNEUMONIA',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    40,
    '2412000104884',
    TO_DATE('05/05/2026', 'DD/MM/YYYY'),
    TO_DATE('09/05/2026', 'DD/MM/YYYY'),
    4,
    'A90',
    'DENGUE',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    41,
    '1100300109061',
    TO_DATE('28/05/2026', 'DD/MM/YYYY'),
    TO_DATE('05/06/2026', 'DD/MM/YYYY'),
    8,
    'K35',
    'APENDICITE',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    42,
    '1100200253987',
    TO_DATE('25/01/2026', 'DD/MM/YYYY'),
    TO_DATE('27/01/2026', 'DD/MM/YYYY'),
    2,
    'A90',
    'DENGUE',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    43,
    '1400200078484',
    TO_DATE('14/01/2026', 'DD/MM/YYYY'),
    TO_DATE('25/01/2026', 'DD/MM/YYYY'),
    11,
    'A90',
    'DENGUE',
    'URGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    44,
    '1400150081906',
    TO_DATE('28/03/2026', 'DD/MM/YYYY'),
    TO_DATE('10/04/2026', 'DD/MM/YYYY'),
    13,
    'J18',
    'PNEUMONIA',
    'ELETIVO',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    45,
    '4321500058394',
    TO_DATE('25/04/2026', 'DD/MM/YYYY'),
    TO_DATE('28/04/2026', 'DD/MM/YYYY'),
    3,
    'J18',
    'PNEUMONIA',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    46,
    '4313400058807',
    TO_DATE('20/01/2026', 'DD/MM/YYYY'),
    TO_DATE('28/01/2026', 'DD/MM/YYYY'),
    8,
    'J18',
    'PNEUMONIA',
    'ELETIVO',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    47,
    '4205400019283',
    TO_DATE('16/06/2026', 'DD/MM/YYYY'),
    TO_DATE('25/06/2026', 'DD/MM/YYYY'),
    9,
    'J18',
    'PNEUMONIA',
    'ELETIVO',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    48,
    '4205400019305',
    TO_DATE('02/03/2026', 'DD/MM/YYYY'),
    TO_DATE('05/03/2026', 'DD/MM/YYYY'),
    3,
    'E11',
    'DIABETES MELLITUS',
    'EMERGÊNCIA',
    'ADULTO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    49,
    '2804502421089',
    TO_DATE('16/01/2026', 'DD/MM/YYYY'),
    TO_DATE('19/01/2026', 'DD/MM/YYYY'),
    3,
    'K35',
    'APENDICITE',
    'EMERGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    50,
    '2800300002372',
    TO_DATE('27/04/2026', 'DD/MM/YYYY'),
    TO_DATE('02/05/2026', 'DD/MM/YYYY'),
    5,
    'A90',
    'DENGUE',
    'EMERGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    51,
    '3534400008028',
    TO_DATE('23/05/2026', 'DD/MM/YYYY'),
    TO_DATE('03/06/2026', 'DD/MM/YYYY'),
    11,
    'U07.1',
    'COVID-19',
    'URGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    52,
    '3547800008737',
    TO_DATE('15/01/2026', 'DD/MM/YYYY'),
    TO_DATE('25/01/2026', 'DD/MM/YYYY'),
    10,
    'A90',
    'DENGUE',
    'URGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    53,
    '1702200049298',
    TO_DATE('13/01/2026', 'DD/MM/YYYY'),
    TO_DATE('23/01/2026', 'DD/MM/YYYY'),
    10,
    'A90',
    'DENGUE',
    'URGÊNCIA',
    'IDOSO',
    'ALTA'
);

INSERT INTO TB_INTERNACOES (
    ID_INTERNACAO,
    CO_UNIDADE,
    DATA_INTERNACAO,
    DATA_ALTA,
    TEMPO_PERMANENCIA,
    CID,
    DOENCA,
    TIPO_ATENDIMENTO,
    FAIXA_ETARIA,
    STATUS
)
VALUES (
    54,
    '1702550069078',
    TO_DATE('15/01/2026', 'DD/MM/YYYY'),
    TO_DATE('24/01/2026', 'DD/MM/YYYY'),
    9,
    'J45',
    'ASMA',
    'EMERGÊNCIA',
    'CRIANÇA',
    'ALTA'
);

COMMIT;
